### ISSUE TITLE
Scikit learn instead of sklearn

### ISSUE THREAD

**Issue by eyadsibai** [tmadl/semisup-learn#9]
https://github.com/tmadl/semisup-learn/blob/82ad804b3f7472d89ae629c3c689c5920edce006/setup.py#L10

I believe this should be scikit-learn instead of sklearn

**Comment by Pr0duktiv** [comment]
The short name of the Scikit-Learn package (which you'll use to import it) is 'sklearn'

**Comment by Pr0duktiv** [comment]
Works for me. Does it say `Collecting scikit-learn (from sklearn->semisup-learn==0.0.1)` during the installation process? You may want to update pip if it can't find scikit-learn via sklearn

**Comment by eyadsibai** [comment]
it is installing a package called sklearn!! then sklearn package requires scikit-learn it is a different package. there is already a package called sklearn. This is not working as intended. Go check the documentation of scikit-learn and how it should be installed. No other project uses sklearn in the requirements.txt
Read the project description please!
https://pypi.org/project/sklearn/

**Comment by Pr0duktiv** [comment]
I am aware of this, but you should still be able to install it via sklearn. It is planned to remove this functionality (https://github.com/scikit-learn/scikit-learn/issues/8215), but it should still work. Why don't you submit a PR if you want to change it?

**Comment by eyadsibai** [comment]
part of open source contribution is to submit such issues. Not necessary submitting PRs. If you don't like this issue, then thank you, though u r not the owner nor the contributor of this repo.

**Comment by Pr0duktiv** [comment]
> though u r not the owner nor the contributor of this repo.

Thanks for pointing that out, I didn't know!

**Comment by lesteve** [comment]
FYI I have opened #10 to fix that.
